name: Health Check

on:
  schedule:
    - cron: '00 15 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.WEB_URL }}/health
